Story4/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/urls.py
from django.urls import path
from .views import savematkul , readmatkul , deletematkul, hasilcari

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('help',views.help, name='help'),
    path('home',views.home, name='home'),
    path('cari',views.cari, name='cari'),
    path('delete',views.delete, name='delete'),
    path('savematkul', views.savematkul),
    path('readmatkul', readmatkul),
    path('deletematkul', deletematkul),
    path('data/', views.hasilcari),
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
     path('logout/', views.logoutUser, name='logout'),
    
    
]

story6/urls.py
from django.urls import path

from . import views

app_name = 'story6'

urlpatterns = [
    path('story6', views.story6, name='story6')
]

main/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime, date
# Create your models here.
class Matkul(models.Model):
    name = models.CharField(max_length=30)
    dosen =  models.CharField(max_length=30)
    sks = models.CharField( max_length=3)

class Post(models.Model):
    author = models.ForeignKey(Matkul, on_delete= models.CASCADE)
    content = models.CharField(max_length = 125)
    published_date = models.DateTimeField(default = timezone.now)

story6/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms
from .models import Matkul
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class Input_Form(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = ['name','dosen','sks']
        fields = '__all__'
    error_massages = {
        'required' : 'please type'
    }
    input_attrs = {
        'type' : 'text',
        'placeholder' : 'masukan matkul'
    }
    input_attrs1 = {
        'type' : 'text',
        'placeholder' : 'masukan dosen'
    }
    input_attrs2 = {
        'type' : 'text',
        'placeholder' : 'masukan sks'
    }
    name = forms.CharField(label = ' ', required = True , max_length=27 , widget=forms.TextInput(attrs=input_attrs))
    dosen = forms.CharField(label = ' ', required = True , max_length=27 , widget=forms.TextInput(attrs=input_attrs1))
    sks = forms.CharField(label = ' ', required = True , max_length=27 , widget=forms.TextInput(attrs=input_attrs2))

class Delete_Form(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = ['name']   
    error_massages = {
        'required' : 'please type'
    }
    input_attrs = {
        'type' : 'text',
        'placeholder' : 'delete matkul'
    }
    name = forms.CharField(label = ' ', required = True , max_length=27 , widget=forms.TextInput(attrs=input_attrs))

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .forms import Input_Form , Delete_Form, CreateUserForm
from .models import Matkul , Post 
from django.http import JsonResponse

from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

import json
import requests


def home(request):
    return render(request, 'main/home.html')

# @login_required(login_url='main:login')
def help(request):
    response = {'input_form' : Input_Form}
    return render(request, 'main/help_extention.html', response)

def cari(request):
    
    return render(request, 'main/cari_buku.html')

def savematkul(request):
    form = Input_Form(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        form.save()
        return HttpResponseRedirect('/readmatkul')
    else:
        return HttpResponseRedirect('/home')

def readmatkul(request):
    matkuls = Matkul.objects.all()   
    response = {'matkuls' : matkuls,}
    return render(request, 'main/home.html' , response)

# @login_required(login_url='main:login')
def delete(request):
    response = {'delete_form' : Delete_Form}
    return render(request, 'main/delete.html', response)


def deletematkul(request):
    form = Delete_Form(request.POST or None)
    if (form.is_valid and request.method == 'POST'):
        Matkul.objects.filter(name=form).delete()
        return HttpResponseRedirect('/readmatkul')
    else:
        return HttpResponseRedirect('/home')

def hasilcari(request):
    arg= request.GET['q']
    url_tujuan = 'https://www.googleapis.com/books/v1/volumes?q=' + arg
    r = requests.get(url_tujuan)

    data = json.loads(r.content)
    return JsonResponse(data, safe=False)

def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created (name : ' + user + ')')
            return redirect('main:login')

    response = {'form' : form}
    return render(request, 'main/register.html', response)

def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('main:home')
        else:
            messages.info(request, 'username OR password in incorrect')
           

    response = {}
    return render(request, 'main/login.html', response)

def logoutUser(request):
    logout(request)
    return redirect('main:login')

story6/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
# Create your views here.

def story6(request):
    return render(request, 'story6/story6.html')

main/templates/main/cari_buku.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% block meta %}
    <head>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
        <title>THIS IS MY NEW DESIGN</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    </head>
    {% endblock meta %}
    {% block content %}
    <body>
        <input type="checkbox" id="check">

        <header>
            <label for="check"> 
                <i class="fab fa-elementor" id="left_sidebar_menu"></i>
            </label>
            <div class="left">
                <h3>S<span>ALVI</span>AN</h3>
            </div>
            <div class="right">
                <a href="home" class="help_button">Back</a>
            </div>
        </header>

        <div class="left_sidebar">
            <div>
                <h4 style="text-align: center;">Mohon Maaf <br> Belum Tersedia</h4>
            </div>
            
        </div>
        <div class="web_content"  style="background: url('/static/img/grass_background.jpg') no-repeat top center fixed; background-size: cover;">
            <h2 style="background-color: rgb(92, 92, 92, 0.5);">Cari Buku<br >
                <input id="keyword" placeholder="masukan kata" size="30px">
                <ol id= "hasil" style="text-align: left; padding-left: 100px;">

                </ol>
            </h2>
        </div>

        
    </body>
    
    <script type="text/javascript">
        $("#keyword").keyup( function(){
            var isi_keyword = $("#keyword").val();
            var url_data = '/data?q=' + isi_keyword;

            $.ajax({
                url: url_data,
                success: function(hasil) {
                    console.log(hasil.items);
                    var obj_hasil = $("#hasil");
                    obj_hasil.empty();

                    for(i = 0 ; i < hasil.items.length; i++){
                        var tmp_title = hasil.items[i].volumeInfo.title;
                        var tmp_thumbnails = hasil.items[i].volumeInfo.imageLinks.smallThumbnail;
                        var temp_link = hasil.items[i].volumeInfo.previewLink;
                        var temp_info = hasil.items[i].searchInfo.textSnippet;
                        console.log(tmp_title);
                        obj_hasil.append('<li style="border: 2px solid orange;background-color: rgba(0, 0, 0, 0.5);"> ' + tmp_title + '<br> <img src=' 
                        + tmp_thumbnails + ' style="border-radius: 150px;margin-left: 50px;">'+'<h6>'+ temp_info +'</h6>'+ '<a href="'+ temp_link +'"><h6>'+ 
                        temp_link+'</h6></a>'+'</li>'); 
                    }
                }
            })
        })
    </script>
    {% endblock content %}



</html>

main/templates/main/delete.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% block meta %}
    <head>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
        <title>THIS IS MY NEW DESIGN</title>
    </head>
    {% endblock meta %}
    {% block content %}
    <body>
        <input type="checkbox" id="check">

        <header>
            <label for="check"> 
                <i class="fab fa-elementor" id="left_sidebar_menu"></i>
            </label>
            <div class="left">
                <h3>S<span>ALVI</span>AN</h3>
            </div>
            <div class="right">
                <a href="home" class="help_button">Back</a>
            </div>
        </header>

        <div class="left_sidebar">
            <div>
                <h4 style="text-align: center;">Mohon Maaf <br> Belum Tersedia</h4>
            </div>
            
        </div>
        <div class="web_content"  style="background: url('/static/img/grass_background.jpg') no-repeat top center fixed; background-size: cover;">
           <h2>
            <form action="deletematkul" method="POST" style="background-color: rgb(92, 92, 92, 0.5); background-size: 100px;">
                {% csrf_token %}
                Masukan Matkul yang ingin didelete {{ delete_form.as_p}}
                <input type="submit" value="Delete"><br><br><br>
            </form>
            </h2>>
        </div>

        
    </body>
    {% endblock content %}


</html>

main/templates/main/help_extention.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
    {% block meta %}
    <head>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
        <title>THIS IS MY NEW DESIGN</title>
    </head>
    {% endblock meta %}
    {% block content %}
    <body>
        <input type="checkbox" id="check">

        <header>
            <label for="check"> 
                <i class="fab fa-elementor" id="left_sidebar_menu"></i>
            </label>
            <div class="left">
                <h3>S<span>ALVI</span>AN</h3>
            </div>
            <div class="right">
                <a href="home" class="help_button">Back</a>
            </div>
        </header>

        <div class="left_sidebar">
            <div>
                <h4 style="text-align: center;">Mohon Maaf <br> Belum Tersedia</h4>
            </div>
            
        </div>
        <div class="web_content"  style="background: url('/static/img/grass_background.jpg') no-repeat top center fixed; background-size: cover;">
           <h2>
            <form action="savematkul" method="POST" style="background-color: rgb(92, 92, 92, 0.5); background-size: 100px;">
                {% csrf_token %}
                Masukan data mata kuliah {{ input_form.as_p}}
                <input type="submit" value="Submit"><br><br><br>
            </form>
            </h2>>
        </div>

        
    </body>
    {% endblock content %}


</html>

main/templates/main/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #383838 !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: rgb(224, 155, 64);
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #3ebce6 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #a7a7a7 !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
                            </div>
                               
                        
                    </form>
                   


				</div>
             
                {% for message in messages%}
                    <p id="messages">{{message}}</p>
                {% endfor %}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
                        Don't have an account? <a href="{% url 'main:register' %}"  class="ml-2">Sign Up</a>
                    </div>
                    <a href="{% url 'main:home' %}" style="margin-left: 150px;">Home</a>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

main/templates/main/register.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
 
{% block meta %}
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: rgb(224, 155, 64)!important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #636363;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #2eb8e6 !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
{% endblock meta %}
{% block content %}
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							{{form.username}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							{{form.email}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password1}}
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							{{form.password2}}
						</div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
                
                {{form.errors}}

				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'main:login' %}"  class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Enter password...';
		form_fields[4].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
{% endblock content %}

</html>

story6/templates/story6/story6.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>ini story 6</title>
    </head>
    <body>
        
    </body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
</body>
  {% block content %}
  {% endblock content %}
</html>